### ISSUE TITLE
Binder link does not start

### ISSUE THREAD

**Issue by habi** [TomographicImaging/CIL-Demos#53]
I get an error on Binder when starting the [notebooks](https://mybinder.org/v2/gh/TomographicImaging/CIL-Demos/HEAD?urlpath=lab/tree/binder%2Findex.ipynb).
The screenshot of the error is below

![Screenshot from 2021-09-03 10-41-32](https://user-images.githubusercontent.com/1651235/131977119-640e71bc-0afb-4f36-a2a1-d6a8119e6bb0.png)

**Comment by paskino** [comment]
Thanks. I guess the problem is that the channels are `ccpi/label/dev` rather than the stable one.

**Comment by epapoutsellis** [comment]
The environment of binder is updated and the link works.
